In [3]:
import numpy as np
from scipy.optimize import linprog
import pandas as pd


# Matrix treatment:
def nn2na(NN):
    # Get every location where exist an arc:
    idxs = np.argwhere(NN)
    # Preallocate NA matrix, dimension is (nodes, arcs)
    NA = np.zeros([NN.shape[0], idxs.shape[0]]).astype(int)
    C = np.zeros(NA.shape[1])
    # Loop in every arc, complete from (1) to (-1)
    for i, arc in enumerate(idxs):
        # Node arc:
        NA[arc[0], i] = 1 # From
        NA[arc[1], i] = -1 # To

    arc_idxs = [(arc[0], arc[1]) for arc in idxs]

    return NA, arc_idxs


#importo la matriz
NN = np.array([[0, 1, 1, 0, 0, 0],
               [0, 0, 0, 1, 0, 1],
               [0, 0, 0, 0, 1, 0],
               [0, 0, 0, 0, 0, 1],
               [0, 0, 0, 0, 0, 1],
               [0, 0, 0, 0, 0, 0]])
#manipulo la data
C = np.array([2,2,2,5,2,1,2])
Aeq, arc_idxs=nn2na(NN)
Beq = np.array([1,0,0,0,0,-1])
Bounds = tuple([(0, None) for arcs in range (0, Aeq.shape[1])])

print('## Optimizer inputs ## \n'
      'cost vector: %s \n'
      'A_eq Node_arc Matrix: \n%s \n'
      'b_eq Demand supply vector: %s \n'
      'Bounds of each X arc varible: %s \n' % (C, Aeq, Beq, Bounds))
      
#Optimizo el probl
#res = linprog (C, A_eq=Aeq , B_eq=Beq , Bounds=Bounds)


      

## Optimizer inputs ## 
cost vector: [2 2 2 5 2 1 2] 
A_eq Node_arc Matrix: 
[[ 1  1  0  0  0  0  0]
 [-1  0  1  1  0  0  0]
 [ 0 -1  0  0  1  0  0]
 [ 0  0 -1  0  0  1  0]
 [ 0  0  0  0 -1  0  1]
 [ 0  0  0 -1  0 -1 -1]] 
b_eq Demand supply vector: [ 1  0  0  0  0 -1] 
Bounds of each X arc varible: ((0, None), (0, None), (0, None), (0, None), (0, None), (0, None), (0, None)) 

